[package]
name = "xorfilter-rs"
version = "0.2.0"
authors = ["prataprc <prataprc@gmail.com>"]
edition = "2018"
description = "Xor Filters: Faster and Smaller Than Bloom and Cuckoo Filters"
license = "Apache-2.0"
documentation = "https://docs.rs/xorfilter-rs"
homepage = "https://github.com/bnclabs/xorfilter"
repository = "https://github.com/bnclabs/xorfilter"

[lib]
name = "xorfilter"

[workspace]
members = ["benches"]

[dependencies]

[dev-dependencies]
rand = "0.8.4"


[profile.release]
debug = true

[profile.bench]
debug = true