name: simple-build-test

on: [push]

jobs:
  build:
    name: xorfilter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build stable dev
      run: cargo +stable build --verbose
    - name: Build stable release
      run: cargo +stable build --verbose --release
    - name: Test stable dev
      run: cargo +stable test --verbose
    - name: Test stable release
      run: cargo +stable test --verbose --release
