name: simple-build-test

on: [push]

jobs:
  build:
    name: xorfilter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly

    - name: Build
      run: cargo build --verbose
    - name: Build release
      run: cargo build --verbose --release
    - name: Run dev tests
      run: cargo test --verbose
    - name: Run release tests
      run: cargo test --verbose --release
    - name: Run dev benchmarks
      run: cargo +nightly bench --verbose
    - name: Run release benchmarks
      run: cargo +nightly bench --verbose --release
