name: simple-build-test

on: [push]

jobs:
  build:
    name: xorfilter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      run: cargo build --verbose --release
    - name: Run release tests 
      run: cargo test --verbose --release
