name: simple-build-test

on: [push]

jobs:
  build:
    name: xorfilter-stable
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Build release
      run: cargo build --verbose --release
    - name: Run dev tests
      run: cargo test --verbose
    - name: Run release tests
      run: cargo test --verbose --release

jobs:
  build:
    name: xorfilter-nightly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        toolchain: nightly
    - name: Run dev benchmarks
      run: cargo bench --verbose
    - name: Run release benchmarks
      run: cargo bench --verbose --release
